app:
  proj_title: CMS Demo
  theme: darkly
  navbar_pages:
    Home: /
    Register: /register
    Sign Up: /sign-up
  marketing_ids:
    google_ads:
    google_event:
    facebook_pixel:
    twitter_pixel:
    linkedin_partner:
    perfect_audience:
  social_media:
    amazon: https://www.amazon.com/author/revmichaelhoyt
    facebook: https://www.facebook.com/SaintsBeTold/
    instagram: https://www.instagram.com/economyofdreams
    twitter: https://twitter.com/SaintsBeTold
    linkedin: https://www.linkedin.com/in/economyofdreams
    youtube: https://youtube.com/channel/UCNx9OlImFLIp9zYI9xteX9g
  contact:
    phone: '+12698610617'
    email: 'mike@saintsbetold.org'
    mail: 'Michael Hoyt, 1950 W Corporate Way #70122, Anaheim, CA 92801'

blueprints:
  pages:
    - index:
        foo: bar
    - sign-up:
    - register:
    - terms-of-use:
    - privacy-policy:
  affiliates:
    - google:
        affiliate_url: '/'
        foo: bar