app:
  proj_title: CMS Demo
  theme: darkly
  navbar_pages:
    Home: /
    Register: /register
    Sign Up: /sign-up
  marketing_ids:
    google_ads:
    google_event:
    facebook_pixel:
    twitter_pixel:
    linkedin_partner:
    perfect_audience:

blueprints:
  index:
    foo: bar
  forms:
    - sign-up:
    - register:
  policies:
    - terms-of-use:
    - privacy-policy:
  affiliates:
    - google:
        affiliate_url: '/'
        foo: bar