app:
  proj_title: CMS Demo
  canonical_url: https://content-management-syste-a9bb6.web.app
  jsonld_id: 'M#vF_X&-FcRT.rL.y=.cUAdj[=q?#GH2'
  gtm: W8J9GD7
  theme: pulse
  navbar_pages:
    Home: /
    Register: /register
    Sign Up: /sign-up
  social_media:
    amazon: https://www.amazon.com/author/revmichaelhoyt
    facebook: https://www.facebook.com/SaintsBeTold/
    instagram: https://www.instagram.com/economyofdreams
    twitter: https://twitter.com/SaintsBeTold
    linkedin: https://www.linkedin.com/in/economyofdreams
    youtube: https://youtube.com/channel/UCNx9OlImFLIp9zYI9xteX9g
  contact:
    phone: '+12698610617'
    email: 'mike@saintsbetold.org'
    mail: 
        street: '1950 W Corporate Way #70122'
        city: Anaheim
        state: CA 
        postal: '92801'

blueprints:
  pages:
    - index:
        img: 
            webp: /static/img/foobar.webp
            other: /static/img/foobar.png
        description: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
    - sign-up:
        title: Sign Up
        img: 
            webp: /static/img/foobar.webp
            other: /static/img/foobar.png
        description: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
    - register:
        title: Register
        img: 
            webp: /static/img/foobar.webp
            other: /static/img/foobar.png
        description: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
    - terms-of-use:
        title: Terms of Use
        description: Terms of Use
    - privacy-policy:
        title: Privacy Policy
        description: Privacy Policy
  affiliates:
    - google:
        affiliate_url: '/'