app:
  proj_title: CMS Demo
  canonical_url: https://content-management-syste-a9bb6.web.app
  theme: pulse
  navbar_pages:
    Home: /
    Register: /register
    Sign Up: /sign-up
  marketing_ids:
    google_ads: '655324231'
    google_event: '-byqCK6OvcsBEMfovbgC'
    facebook_pixel: '1466474223384257'
    twitter_pixel: 'o3fgf'
    linkedin_partner: '2054625'
    perfect_audience: '5e6427d5e8b846a1d1000013'
  social_media:
    amazon: https://www.amazon.com/author/revmichaelhoyt
    facebook: https://www.facebook.com/SaintsBeTold/
    instagram: https://www.instagram.com/economyofdreams
    twitter: https://twitter.com/SaintsBeTold
    linkedin: https://www.linkedin.com/in/economyofdreams
    youtube: https://youtube.com/channel/UCNx9OlImFLIp9zYI9xteX9g
  contact:
    phone: '+12698610617'
    email: 'mike@saintsbetold.org'
    mail: 'Michael Hoyt, 1950 W Corporate Way #70122, Anaheim, CA 92801'

blueprints:
  pages:
    - index:
        title: Homepage
        img: /static/img/foobar.png
    - sign-up:
    - register:
    - terms-of-use:
    - privacy-policy:
  affiliates:
    - google:
        affiliate_url: '/'
        foo: bar